disable_existing_loggers: false
version: 1
formatters:
  standard:
    datefmt: "%Y-%m-%d %H:%M:%S %z"
    format: "%(asctime)s [%(levelname)s]%(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    stream: ext://sys.stdout
root:
  handlers:
    - console
  level: INFO
