# run build and unit test to ensure the template is in working condition

on:
  push:
    branches:
    - develop
    - main

  pull_request:
    branches:
    - develop
    types: [opened, edited, reopened]

  workflow_dispatch:

jobs:
  python-test-and-build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.5"
        enable-cache: true

    - name: Install Python using uv ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync

    - name: Linting
      if: success()
      run: |
        uv run ruff check .

    - name: Configure Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"

    - name: Unit tests
      run: |
        uv run pytest -v -s
