# run build and unit test to ensure the template is in working condition

on:
  push:
    branches:
    - develop
    - main
    - uv

  pull_request:
    branches:
    - develop
    types: [opened, edited, reopened]

  workflow_dispatch:

jobs:
  python-test-and-build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: Linting
      if: success()
      run: |
        uv run ruff check .

    - name: Configure Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"

    - name: Unit tests
      run: |
        uv run pytest -v -s
